# Generated by Django 3.0.5 on 2020-05-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0002_auto_20200503_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apresentacao',
            new_name='Banca',
        ),
    ]
