# Generated by Django 3.0.5 on 2020-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0004_auto_20200606_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='nome',
            field=models.CharField(default='Grade 1', max_length=50),
            preserve_default=False,
        ),
    ]
