# Generated by Django 3.0.5 on 2020-06-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0006_banca_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TccAdmin.Horario'),
            preserve_default=False,
        ),
    ]
