# Generated by Django 3.0.5 on 2020-06-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0007_auto_20200607_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradeTcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='preenchido',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='grade',
        ),
        migrations.AddField(
            model_name='horario',
            name='preenchido_banca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='preenchido_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='gradetcc',
            name='horarios',
            field=models.ManyToManyField(to='TccAdmin.Horario'),
        ),
        migrations.AddField(
            model_name='gradeaula',
            name='horarios',
            field=models.ManyToManyField(to='TccAdmin.Horario'),
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TccAdmin.GradeAula'),
        ),
    ]
