# Generated by Django 3.0.5 on 2020-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0008_auto_20200607_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetcc',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
