# Generated by Django 3.0.7 on 2020-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0009_gradetcc_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banca',
            name='observacao',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
