# Generated by Django 3.0.7 on 2020-06-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0010_banca_observacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
