# Generated by Django 3.0.5 on 2020-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TccAdmin', '0011_auto_20200608_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='observacao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
